config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#welcome'

  resources :users, only: [:new, :create, :show]

  resources :posts do
    resources :likes
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  def self.num_likes
    self.all.count
  end
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_one_attached :picture
    has_many :comments


    def self.number_of_posts
        self.all.count
    end

    def self.most_liked_post
        l_post = nil
        l_count = 0
        self.all.each do |post|
            if post.likes.count > l_count
                l_post = post
                l_count = post.likes.count
            end
        end
        l_post
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :posts, dependent: :delete_all
    has_many :items
    has_many :comments, through: :posts
    has_many :likes, dependent: :destroy
    validates :username, uniqueness: true 

    def self.total_users
        User.count
    end

    def self.most_posts
        u = nil
        i = 0 
        self.all.each do |user|
            if user.posts.count >= i
                u = user
                i = user.posts.count
            end
        end
        u
    end

    def self.most_likes
        u = nil
        i = 0 
        self.all.each do |user|
            if user.likes.count >= i
                u = user
                i = user.likes.count
            end
        end
        u
    end

    def self.lucky
        self.all[rand(self.all.count)]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authorized
    helper_method :current_user
    helper_method :logged_in?

    def current_user
        User.find_by(id: session[:user_id])
    end

    def logged_in?      
        !current_user.nil?
    end

    def authorized
        redirect_to '/welcome' unless logged_in?
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_post
    before_action :find_like, only: [:destroy]

    def create
        if already_liked?
            flash[:notice] = "You can't like more than once"
        else
            @post.likes.create(user_id: current_user.id)
        end
        redirect_to post_path(@post)
    end

    def destroy
        if !(already_liked?)
            flash[:notice] = "Cannot unlike"
        else
            @like.destroy
        end
    redirect_to post_path(@post)
    end

    private

    def find_post
        @post = Post.find(params[:post_id])
    end

    def already_liked?
        Like.where(user_id: current_user.id, post_id: params[:post_id]).exists?
    end

    def find_like
        @like = @post.likes.find(params[:id])
    end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
    @user = Post.all
  end
  
  def create
    @post = Post.create
  end
  
  def show
    @post = Post.all
  end
  
  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_params(@post)
  end
  
  def destroy
    Post.find(params[:id]).destroy
    redirect_to post_params
  end
  
  private
  
  def post_params
    params.require(:user).permit(:name, :username, :email, :password)
  end
end
  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.sort_by{|post| post.likes.count}.reverse
  end

  def show
  end
  
  def new
    @post = Post.new
  end

  def create
    @user = User.find(session[:user_id])
    @post = Post.new(title: params[:post][:title], description: params[:post][:description], user: current_user)
    @post.picture.attach(params[:post][:picture])
    if @post.valid?
      @post.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to @post
  end
  
  def destroy
    @post.destroy
    redirect_to posts_path
  end
  
  private

  def find_post
    @post = Post.find(params[:id])
  end
  
  def post_params
    params.require(:post).permit(:title, :pictures [], :description, :user_id)
  end
end
  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :authorized, only: [:new, :create, :welcome]

    def new
    end
    
    def login
    end

    def create
      @user = User.find_by(username: params[:username])
      if @user && @user.authenticate(params[:password])
         session[:user_id] = @user.id
         redirect_to user_path(@user)
      else
         redirect_to '/login'
      end
    end
  
    def destroy
      session.delete(:user_id)
      redirect_to root_url
    end

    def page_requires_login
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @user = User.all
  end

  def create
    @user = User.create
      if @user.save
        redirect_to :action => post_url
      else
        render :action => post_url
      end
  end

  def show
    @user = User.all
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to user_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to '/welcome'
    else
      render 'new'
    end
    
  end

  def show
    @user = User.find_by(id: params[:id])
    @posts = @user.posts
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InteriorDesign</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<body bgcolor="#b2bec3">
<div class="profilelogo"></div>
<div class="siteheaders">
<h1>Featured Post</h1>
</div>
<br>
<div class="profile">
<h1><%= link_to current_user.username, user_path(current_user.id) %></h1>
</div>
<%= button_to "Log out", '/logout', method: :delete %>

<%= button_to "Create Post", '/posts/new', method: :get%>
<div class="profile">
<h1><%= link_to current_user.username, user_path(current_user.id) %></h1>
</div>
<div class="whitespacecontainer">
    <div class="whitespace">
    <ul>
        <%= @posts.each do |post|%>
            <% @post_owner = User.find_by(id: post.user_id) %>     
            
            <h3><%= link_to post.title, post_path(post) %> by <%= link_to @post_owner.username, user_path(@post_owner.id) %></h3>
            <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>

            <image src="<%=(url_for(post.picture)) %>">
            <p><%= post.description %></p>
        <%end%>
    </ul>
    </div>
</div>

app/views/posts/new.html.erb
<body bgcolor="#b2bec3">
<div class="logo">
<h1 align = "center"></h1>
</div>

<h1 align = "center">Make a new post</h1>
<div class="profile">
<h1><%= link_to current_user.username, user_path(current_user.id) %></h1>
</div>
<ul>
<%= form_for(@post) do |f| %>
    <div class="buttons">
    <%= f.label :title %>
    <%= f.text_field :title %><br>

    <%= f.label :picture %>
    <%= f.file_field :picture %><br>

    <%= f.label :description %>
    <%= f.text_field :description %><br>
    
    <%= f.submit %>
    </div>
<% end %>
</ul>

app/views/posts/show.html.erb
<body bgcolor="#b2bec3">
<div class="profilelogo"></div>
<div class="siteheaders">
<h1><%= @post.title %></h1><br>
</div>

<div class="whitespacecontainer">
  <div class="whitespace">
    <%= button_to "Featured Posts", '/posts', method: :get%>

      <p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
      <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
      <% if pre_like %>
        <%= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete %>
      <% else %>
        <%= button_to 'Like', post_likes_path(@post), method: :post %>
      <% end %>

      <% if @post.user_id == session[:user_id] %> 
        <%= button_to "Delete Post", @post, method: :delete %>   
      <% end %>
      <p><%= @post.description %></p>

      <image src="<%=(url_for(@post.picture))%>"><br>
  </div>
</div>

app/views/user/new.html.erb
<h1>Create a Account</h1>

<ul>
  <%= form_for @luxx do |x| %>
    <%= x.label :name %><br>
    <%= x.text_field :name, placeholder: "Name" %><br>
    <%= x.label :username %><br>
    <%= x.text_field :username, placeholder: "Username"  %><br>
    <%= x.label :email  %><br>
    <%= x.text_field :email, placeholder: "Email"  %><br>
    <%= x.label :password%><br>
    <%= x.password_field :password, placeholder: "Password"%><br>
    <%= x.submit "Create" %>
  <%end%>
</ul>

app/views/users/create.html.erb
<body bgcolor="#b2bec3">
<div class="logo">
<h1 align = "center"></h1>
</div>

<h1 align = "center">Create a Account</h1>

<ul>
  <%= form_for @user do |x| %>
    <div class="buttons">
    <%= x.label :name %><br>
    <%= x.text_field :name, placeholder: "Name" %><br>
    <%= x.label :username %><br>
    <%= x.text_field :username, placeholder: "Username"  %><br>
    <%= x.label :email  %><br>
    <%= x.text_field :email, placeholder: "Email"  %><br>
    <%= x.label :password%><br>
    <%= x.password_field :password, placeholder: "Password"%><br>
    <%= x.submit "Create" %>
  <%end%>
  </div>
</ul>

app/views/users/new.html.erb
<body bgcolor="#b2bec3">
<div class="logo">
<h1 align = "center"></h1>
</div>
<h1 align="center">Sign Up</h1>
</div>

<%= form_for @user do |f|%>
  <div class="buttons">
  <%= f.label :username%>
  <%= f.text_field :username%><br>
  <%= f.label :password%>
  <%= f.password_field :password%><br>
  <%= @user.errors.full_messages.first if @user.errors.any? %><br>
  <%= f.submit %>
  </div>
  
<%end%>

app/views/users/show.html.erb
<body bgcolor="#b2bec3">
<div class="profilelogo"></div>
<div class="siteheaders">
<h1><%= @user.username %>'s Posts</h1>
</div>
<%= button_to "Featured Posts", '/posts', method: :get%>
<%= button_to "Create Post", '/posts/new', method: :get%>

<div class="whitespacecontainer">
    <div class="whitespace">
    <ul>
        <%= @posts.each do |post|%>
            <h3><%= link_to post.title, post_path(post) %></h3>
            <image src="<%=(url_for(post.picture))%>">
        <%end%>
    </ul>
    </div>
</div>